# 实现一个可取消的Promise
简单说来，这里的可取消并不是真的将promise的任务终止了，而是不返回promise中的值，以一个error代替

实现Promise功能扩展的通用方法就是promise 包装，类似于proxy实现 resolve，reject接管。在之前的并发Promise 中也是同样的思想。实现超时管理的promise 也是同样
```
```的思想
```TS
export class CancelFetchError extends Error {
  // 所有实例共享同一个symbol
  static symbol = Symbol.for('CancelFetchError');
  // 使用返回is谓语可以在该函数被执行后让编译器推断出v是否是该类型
  static is(v: any): v is CancelFetchError {
    return v && v._type === CancelFetchError.symbol;
  }
  protected _type = CancelFetchError.symbol;
}

const makeCancelable = (promise) => {
    let isCanceled = false;
    const wrappedPromise = new Promise((resolve, reject) => {
        promise
            .then((val) => isCanceled ? reject(new CancelFetchError()) : resolve(val))
            .catch(error => isCanceled ? reject(new CancelFetchError()) : reject(error));
    });
    return {
        promise: wrappedPromise,
        cancel() {
            isCanceled = true;
        }
    };
};
```